spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/gamingverse
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    liquibase:
        enabled: true
        change-log: classpath:database/changelog/db.changelog-main.xml
